apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: platform-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Sofiamoreta/my-k8s-platform
  ref:
    branch: main
