apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: users-prod
  namespace: flux-system
spec:
  interval: 1m
  path: ./kustomize/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-charts
  targetNamespace: default
